### ISSUE TITLE
html template bug

### ISSUE THREAD

**Issue by gedw99** [mjl-/vex#2] opened 2023-04-14 07:47 UTC
Hey @mjl- 

when downloading a simple golang project ( https://github.com/gedw99/x-git-binary-dummy ) in the Web GUI I got:

``` 

500 - internal server error - server error: executing template: html/template:build:101:187: {{.DownloadFilename}} appears in a JS template literal

``` 

``` 
gobuild serve
listening on http localhost:8000 admin localhost:8001
```

**Comment by mjl-** [comment] 2023-04-14 07:56
Thanks for reporting, that's not good. I suspect it may have started with the latest Go release, this issue in particular https://github.com/golang/go/issues/59272. I'll see if I can get a fix out today, shouldn't be hard.

The issue is for gobuild btw, not vex. But we can leave it here, should be fixed soon enough.

**Comment by mjl-** [comment] 2023-04-14 08:07
I think I fixed it with with the latest commit, new version tagged v0.0.19. Could you give it a try and reopen the issue if it isn't fixed? Thanks for the report!

**Closed by mjl-** 2023-04-14 08:07 UTC

**Comment by gedw99** [comment] 2023-04-14 08:19
Wow that was quick :)
